### PR TITLE
Updated to 1.19.4.

### PR DESCRIPTION
**Pull request by gniftygnome**
Hi!  I am working on porting one of my kids' games forward to 1.19.4 and as part of that I've updated Magic Lanterns.  This PR has been fairly extensively tested but just because of the scope of changes I would say it is at 'beta' grade.

Major user-visible changes:
- Made the various Magic Lanterns lantern blocks water-loggable
- Renamed Biliant Lantern to Brilliant Lantern
- Added recipe advancements

### CODE REVIEW

**Comment by MiusR** [comment]
I didn't expect someone to try to update this mod to a newer version since it's not that interesting. I will take a closer look later today or tomorrow and update this to 1.19.4
After a thorough review you will probably be added as a contribuitor to the mod page as well but I need a name if you have an account

**Comment by gniftygnome** [comment]
I like this mod because it has some fun features Ward Blocks doesn't have and my kids seem to enjoy trying it out.  Also, porting it forward wasn't too difficult but I've done a lot of forward ports of various projects.  I just finished with Desolation, aside from the adding new features to match vanilla part, and that one *was* fairly difficult.

It's a little easier to stumble across Ward Blocks in a modpack because they add their blocks to loot tables all over the place.  We could do a little of that too; f.e. the Life Lantern is fairly early-game and might be fun to add into f.e. the mostly-worthless loot table of the Jungle Temple to spice that up a bit.

BTW having a 1.19.4 version *should* make a 1.20 version pretty easy.  They have tinkered with a few pretty annoying things since 1.19.4 but the main blockers at the moment are probably all screen-related so hopefully Cotton will handle them for us.

If by my account you mean on Curseforge and Modrinth, they are:
CF: gniftygnomecraft
MR: gniftygnome

**Comment by gniftygnome** [comment]
Heh.  I should probably have done a proper version bump on that.  Also looking at the versions I wonder if I based it on the correct branch.  I'll take a look when I get a moment and try to make sure it's not missing anything from 1.4.5.

**Comment by MiusR** [comment]
Oh I didn't even notice that was missing since I looked through the changes made only but it should be fine even without the version bump. The changes made in 1.4.5 were minor and didn't really affect things that much so even if something is missing it can be easily rectified.

**Comment by Fuzss** [comment]
Hey there, I actually made a 1.19+ port a while back released as a separate project under the terms of MIT as [Arcane Lanterns](https://www.curseforge.com/minecraft/mc-mods/arcane-lanterns). 

My versions also includes some overhauls, like data pack based lantern making recipes including JEI support for recipe lookup. Lantern Maker has been reworked, also lanterns extend the vanilla lantern, so things like waterlogging are a given. And most importantly due to my modding toolchain the mod is available for both Fabric and Forge simultaneously.

Just wanted to mention that my port exists and includes many fixes, so no need to duplicate a lot of work there. Also feel free to snatch anything from my port if you want to as it's still essentially your mod!

**Comment by gniftygnome** [comment]
I didn't find that (but I assume the block IDs are different so it would have been a pain for me to use anyway) ... however, I did just recently try to use Leaves Be Gone and it did not work in 1.19.4.  In my experience a lot of mods which are maintained for both Fabric and Forge come out long after the ones which are just for Fabric.  Not intended as a negative comment, it's just two different dev cultures.  I'm rarely in the mood to wait when putting together our next modpack and mostly whatever doesn't make the cut initially doesn't ever.

**Pull request merged**
